server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


